<a href="https://colab.research.google.com/github/kobbii3/mc-202202-JairAcevedo/blob/main/taller13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
vector1 = []
vector2 = []

#VECTOR1
tamaño = int(input("Por favor, Indique la longitud del vector 1 y el vector 2: "))

for i in range(tamaño):
    print("Ingrese el valor ", i + 1, " del vector 1:")
    vector = int(input())
    vector1.append(vector)

print("Vector 1: ", vector1)

#VECTOR2
print("------------------")
for i in range(tamaño):
    print("Ingrese el valor ", i + 1, " del vector 2:")
    vector = int(input())
    vector2.append(vector)

print("Vector 2: ", vector2)

#PRODUCTO ESCALAR
print("------------------")
producto = np.dot(vector1,vector2)
print("Producto escalar: ", producto)

Por favor, Indique la longitud del vector 1 y el vector 2: 2
Ingrese el valor  1  del vector 1:
1
Ingrese el valor  2  del vector 1:
2
Vector 1:  [1, 2]
------------------
Ingrese el valor  1  del vector 2:
3
Ingrese el valor  2  del vector 2:
4
Vector 2:  [3, 4]
------------------
Producto escalar:  11


In [ ]:
#MATRIZ A
filas = int(input("Introduce el número de filas de la matriz A: "))
columnas = int(input("Introduce el número de columnas de la matriz A: "))

x = filas*columnas
valores = list(map(int, input(f"Introduce los {x} valores de la matriz A separados por un espacio:").split()))
matrizA = np.array(valores).reshape(filas,columnas)
print("Matriz A:")
print(matrizA)

#MATRIZ B
print("--------------------")
filas = int(input("Introduce el número de filas de la matriz B: "))
columnas = int(input("Introduce el número de columnas de la matriz B: "))

x2 = filas*columnas
valores = list(map(int, input(f"Introduce los {x2} valores de la matriz B separados por un espacio:").split()))
matrizB = np.array(valores).reshape(filas,columnas)
print("Matriz B:")
print(matrizB)

#OPERACIONES
print("--------------------")
print("OPERACIONES")
print("3A: ", 3*matrizA)
print("4B: ", 4*matrizB)
if x==x2:
  print("A+B: ", matrizA + matrizB)
  print("AxB: ", matrizA * matrizB)

Introduce el número de filas de la matriz A: 3
Introduce el número de columnas de la matriz A: 2
Introduce los 6 valores de la matriz A separados por un espacio:1 2 3 4 5 6
Matriz A:
[[1 2]
 [3 4]
 [5 6]]
--------------------
Introduce el número de filas de la matriz B: 3
Introduce el número de columnas de la matriz B: 3
Introduce los 9 valores de la matriz B separados por un espacio:1 2 3 4 5 6 7 8 9
Matriz B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
OPERACIONES
3A:  [[ 3  6]
 [ 9 12]
 [15 18]]
4B:  [[ 4  8 12]
 [16 20 24]
 [28 32 36]]
