<a href="https://colab.research.google.com/github/kobbii3/mc-202202-JairAcevedo/blob/main/taller15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

def inversa(A):
  #matriz identidad
  tamaño = np.shape(A)
  n = tamaño[0]
  identidad = np.identity(n)

  #matriz aumentada
  AB = np.concatenate((A,identidad),axis=1)
  AB0 = np.copy(AB)

  #pivoteo parcial por filas
  tamaño = np.shape(AB)
  n = tamaño[0]
  m = tamaño[1]

  #para cada fila en AB
  for i in range(0,n-1,1):
      #columna desde diagonal i en adelante
      columna = abs(AB[i:,i])
      max = np.argmax(columna)
      
      #max no está en diagonal
      if (max !=0):
          #intercambia filas
          temporal = np.copy(AB[i,:])
          AB[i,:] = AB[max+i,:]
          AB[max+i,:] = temporal
  AB1 = np.copy(AB)

  #eliminacion hacia adelante
  for i in range(0,n-1,1):
      pivote = AB[i,i]
      adelante = i+1
      for k in range(adelante,n,1):
          factor = AB[k,i]/pivote
          AB[k,:] = AB[k,:] - AB[i,:]*factor
  AB2 = np.copy(AB)

  #elimina hacia atras
  ultfila = n-1
  ultcolumna = m-1
  for i in range(ultfila,0-1,-1):
      pivote = AB[i,i]
      atras = i-1 
      for k in range(atras,0-1,-1):
          factor = AB[k,i]/pivote
          AB[k,:] = AB[k,:] - AB[i,:]*factor
      #diagonal a unos
      AB[i,:] = AB[i,:]/AB[i,i]

  inversa = np.copy(AB[:,n:])
  return inversa

#matrices A y B
A = np.array([[3,2,2],
              [3,1,-3],
              [1,0,-2]], dtype=float)
x = inversa(A)
print('Inversa de A: ')
print(x)

B = np.array([[1,2,0,4],
              [2,0,-1,-2],
              [1,1,-1,0],
              [0,4,1,0]], dtype=float)
y = inversa(B)
print('Inversa de B: ')
print(y)

Inversa de A: 
[[ 1.  -2.   4. ]
 [-1.5  4.  -7.5]
 [ 0.5 -1.   1.5]]
Inversa de B: 
[[ 3.33333333e-01  6.66666667e-01 -6.66666667e-01 -1.38777878e-17]
 [-6.66666667e-02 -1.33333333e-01  3.33333333e-01  2.00000000e-01]
 [ 2.66666667e-01  5.33333333e-01 -1.33333333e+00  2.00000000e-01]
 [ 2.00000000e-01 -1.00000000e-01  0.00000000e+00 -1.00000000e-01]]
